# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de347737b65a1759ec9c86631715cf6ae1da039aafb97d1c1673c8bf9fc2ab5271ef88c04d4b5c023e95ec57a6bbdf2bb9ece1fa16d34497b4785c6aff1ae032

test:
  secret_key_base: a8656ef6a86e2a1e7b51554809c6ecc020a2f53c5e9d5074118c7ad37eac40d6b129623eb0d046d8df3780a9f6d6f73379273f400a29ebe6f75cd210500ebf90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
